### ISSUE TITLE
Posibility of merging proyects :: Net::IPA

### ISSUE THREAD

**Issue by NickCis** [stdweird/p5-net-freeipa#5]
Hi,
i recently find out your project, i've started working with IPA some months ago (using perl) and last week i've uploaded my library: [Net::IPA](https://github.com/NickCis/perl-Net-IPA).

As both projects basically do the same, I was thinking in the posibility of merging projects.

I saw that you retrieve ipa methods from the ipa server, i didn't know that existed. I've wrote the methods that i needed myself.

I'm looking forward to your answer!.

**Comment by stdweird** [comment]
@NickCis i did search before starting, i don't understand how i missed your code.
main issue to using your code however is your license: i'm working on a project that uses apache license, and could thus not use your GPLv3 code.

i'll have a look at your code next week (i'm on holiday this week), to see how it could be integrated.
what timezone do you live/work in? maybe a short skype session to discuss any issues could speed things up? (i'm based in belgium, so CET)

i certainly do not object any features/PRs :smile:

**Comment by NickCis** [comment]
I've started working with perl+ipa some moths ago, but I uploaded the code some weeks ago!. I think we both missed the others code because of that.

I've no problems in changing the project license, as i had not license requirement i just defaulted to GPLv3.

Both codes have good things and bad things. Comparing features, your code implements all api methods (very clever to use that ipa api call in other to retrieve them!). My codes implements user and password login (additional of kerberos) and the batch method. Not all ipa api methods are writen, but there are some useful api aliases (eg.: `dnsrecord_add_a`, `dnsrecord_add_ns`, etc).

Login can be done in three ways:

```
use Net::IPA;
my $ipa = new Net::IPA(
  hostname => 'ipa.server.com',
  cacert => '/etc/ipa/ca.cert',
);

# (a) Login can be done via Kerberos
$ipa->login();

# (b) Login can be done via Kerberos (creating the ticket)
$ipa->login(
  username => 'admin',
  keytab => '/etc/ipa/admin.keytab'
);

# (c) Login can be done using username and password
$ipa->login(
  username => 'admin',
  password => 'admin-password'
);

# Control error
die $ipa->error if($ipa->error);
```

In my implementation throught the [`Net::IPA::Methods`](https://github.com/NickCis/perl-Net-IPA/blob/master/lib/Net/IPA/Methods.pm) module the IPA api is exposed. Calls could be batched in the following way:

```
use Net::IPA::Methods;
my @users_show = $ipa->batch(
  Net::IPA::Methods::user_show('username1'),
  Net::IPA::Methods::user_show('username2'),
  Net::IPA::Methods::user_show('username3'),
);

if(scalar(@users_show) != 3){
  print "Error: 3 requets were done, but only " . (scalar(@users_show)) . " received\n";
  foreach my $r (@users_show){
    print $r->error_string() . "\n" if($r->is_error);
  }
  die 'Error';
}

foreach my $user_show (@users_show){
  # $user_show is of the type Net::IPA::Response
  if($user_show->is_error){
      print 'Error: ' . $user_show->error_string() . "\n";
      next;
  }
  # Do something
}

# If only one request is desired (it is implemented through AUTOLOADing)
my $user_sh = $ipa->user_show('username1');
```

I don't know if i'm missing features from your code. If not, you could help me implement the `get_api` for generating the `Net::IPA::Methods` module, i can change the license to the apache one you need, and we could merge the projects. Does it sound good to you?

I'm from argentina, my time zone is GTM-3, but i do not have any problem in having a skype call late at night.

**Comment by stdweird** [comment]
@NickCis i was asked by one of the freeipa developers to add the dynamic API generation, instead of shipping the full generated API module, so that is on my todo list (altough not very high).
the connection is handled by
https://github.com/stdweird/p5-net-freeipa/blob/master/lib/Net/FreeIPA/RPC.pm#L29
so it does support username/password login, but not the kerberos ticket creation. 
i've briefly looked at your code, you seem to rely on another module for that. there's another catch with  the project i'm working on, i can only use dependencies that are packaged by RHEL and possibly EPEL.

i'm interested in the `batch`, i've seen the API method, but had no time yet to try it out.

i can try to skype this friday april 1st (afternoon for me (14h00-16h00 my time), morning for you (07h00-09h00)); otherwise it will be next week.

**Comment by NickCis** [comment]
@stdweird I have implemented the ticket creation using [Authen::Krb5::Easy cpan module](http://search.cpan.org/~schallee/Authen-Krb5-Easy-0.90/Easy.pm), i had problems with some hardcoded configuration of the module, so i had to modified it. My version is in [github](https://github.com/NickCis/perl-Authen-Krb5-Easy). I've send an email to the developer with no further answer and then, send an email to cpan in order to find out if there is a possibility of becoming the mantainer.

I have no problem in having an skype call this friday (april 1st), i think that you have made a mistake in the hour convertion. CEST is GMT+2 and i'm in GMT-3, your 14h00 will be my 09h00 (and your 16h00 will be my 11h00). We could skype arround [09h00 GMT-3 ARG time (which will be 14h00 CEST)](http://www.timeanddate.com/worldclock/fixedtime.html?p1=51&iso=20160401T09&msg=Skype%20Call&sort=1). I'm `nckcis` on skype or if you prefer hangouts my email is ncis20@gmail.com.

**Comment by stdweird** [comment]
for ticket generation we use http://search.cpan.org/~agrolms/GSSAPI-0.23/GSSAPI.pm
with some debugging/trying it out i made it work, but it is mainly not well documented. short version: gssapi context initialisation can take care of the ticket generation, if you set the keytab using the `KRB5ENV_CLIENT_KEYTAB` environment variable.
e.g. `LWP::Authen::Negotiate` should be able to generate the ticket too (if the principal to use is the default/first principal of the keytab)

https://github.com/stdweird/CAF/blob/kerberos_fixes/src/main/perl/Kerberos.pm is the wrapper i wrote for the project i'm working on, but it mainly there to control the principal and some other forms of safeguarding, like control of the cache.
